#!/usr/bin/env bash
# bash script that displays numbers from 1 to 20

x=1

while [ $x -le 20 ]; do
	case $x in
	4)
		echo -e "$x\nbad luck from China"
		;;
	9)
		echo -e "$x\nbad luck from Japan"
		;;
	17)
		echo -e "$x\nbad luck from Italy"
		;;
	*)
		echo "$x"
		;;
	esac
	((x+=1))
done