#!/usr/bin/env bash
# configure nginx to run from a different user
sed -i '1s/^/user nginx;\n/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]80/listen [::]8080/' /etc/nginx/sites-enabled/default
sudo service nginx restart
